import logo from '../assets/logo.svg';

const Footer = () => {
  return (
    <div className='footer'>
       Royalty Free Images Generated by DALL·E 2   {new Date().getFullYear()}
    </div>
  )
}

export default Footer
